[package]
name = "signal"
version = "0.1.0"
authors = ["Andrew Dona-Couch <signal-rs@andrewcou.ch>"]

[dependencies]
curve25519-dalek = "0.21.0"
rand = "0.5.5"

double-ratchet = { path = "../double-ratchet" }
signal-common = { path = "../signal-common" }
x3dh = { path = "../x3dh" }
